//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/proto/race.proto

package io.github.patxibocos.pcsscraper.protobuf.race;

@kotlin.jvm.JvmSynthetic
inline fun race(block: io.github.patxibocos.pcsscraper.protobuf.race.RaceKt.Dsl.() -> Unit): io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Race =
  io.github.patxibocos.pcsscraper.protobuf.race.RaceKt.Dsl._create(io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Race.newBuilder()).apply { block() }._build()
object RaceKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Race.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Race.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Race = _builder.build()

    /**
     * <code>string id = 1;</code>
     */
    var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>string id = 1;</code>
     */
    fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>string name = 2;</code>
     */
    var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 2;</code>
     */
    fun clearName() {
      _builder.clearName()
    }

    /**
     * <code>string country = 3;</code>
     */
    var country: kotlin.String
      @JvmName("getCountry")
      get() = _builder.getCountry()
      @JvmName("setCountry")
      set(value) {
        _builder.setCountry(value)
      }
    /**
     * <code>string country = 3;</code>
     */
    fun clearCountry() {
      _builder.clearCountry()
    }

    /**
     * <code>.google.protobuf.Timestamp start_date = 4;</code>
     */
    var startDate: com.google.protobuf.Timestamp
      @JvmName("getStartDate")
      get() = _builder.getStartDate()
      @JvmName("setStartDate")
      set(value) {
        _builder.setStartDate(value)
      }
    /**
     * <code>.google.protobuf.Timestamp start_date = 4;</code>
     */
    fun clearStartDate() {
      _builder.clearStartDate()
    }
    /**
     * <code>.google.protobuf.Timestamp start_date = 4;</code>
     * @return Whether the startDate field is set.
     */
    fun hasStartDate(): kotlin.Boolean {
      return _builder.hasStartDate()
    }

    /**
     * <code>.google.protobuf.Timestamp end_date = 5;</code>
     */
    var endDate: com.google.protobuf.Timestamp
      @JvmName("getEndDate")
      get() = _builder.getEndDate()
      @JvmName("setEndDate")
      set(value) {
        _builder.setEndDate(value)
      }
    /**
     * <code>.google.protobuf.Timestamp end_date = 5;</code>
     */
    fun clearEndDate() {
      _builder.clearEndDate()
    }
    /**
     * <code>.google.protobuf.Timestamp end_date = 5;</code>
     * @return Whether the endDate field is set.
     */
    fun hasEndDate(): kotlin.Boolean {
      return _builder.hasEndDate()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class StagesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.Stage stages = 6;</code>
     */
     val stages: com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage, StagesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getStagesList()
      )
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.Stage stages = 6;</code>
     * @param value The stages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addStages")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage, StagesProxy>.add(value: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage) {
      _builder.addStages(value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.Stage stages = 6;</code>
     * @param value The stages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignStages")
    inline operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage, StagesProxy>.plusAssign(value: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage) {
      add(value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.Stage stages = 6;</code>
     * @param values The stages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllStages")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage, StagesProxy>.addAll(values: kotlin.collections.Iterable<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage>) {
      _builder.addAllStages(values)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.Stage stages = 6;</code>
     * @param values The stages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllStages")
    inline operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage, StagesProxy>.plusAssign(values: kotlin.collections.Iterable<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage>) {
      addAll(values)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.Stage stages = 6;</code>
     * @param index The index to set the value at.
     * @param value The stages to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setStages")
    operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage, StagesProxy>.set(index: kotlin.Int, value: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage) {
      _builder.setStages(index, value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.Stage stages = 6;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearStages")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage, StagesProxy>.clear() {
      _builder.clearStages()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class TeamsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.TeamParticipation teams = 7;</code>
     */
     val teams: com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation, TeamsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getTeamsList()
      )
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.TeamParticipation teams = 7;</code>
     * @param value The teams to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTeams")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation, TeamsProxy>.add(value: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation) {
      _builder.addTeams(value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.TeamParticipation teams = 7;</code>
     * @param value The teams to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTeams")
    inline operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation, TeamsProxy>.plusAssign(value: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation) {
      add(value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.TeamParticipation teams = 7;</code>
     * @param values The teams to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTeams")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation, TeamsProxy>.addAll(values: kotlin.collections.Iterable<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation>) {
      _builder.addAllTeams(values)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.TeamParticipation teams = 7;</code>
     * @param values The teams to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTeams")
    inline operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation, TeamsProxy>.plusAssign(values: kotlin.collections.Iterable<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation>) {
      addAll(values)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.TeamParticipation teams = 7;</code>
     * @param index The index to set the value at.
     * @param value The teams to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTeams")
    operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation, TeamsProxy>.set(index: kotlin.Int, value: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation) {
      _builder.setTeams(index, value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.TeamParticipation teams = 7;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTeams")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation, TeamsProxy>.clear() {
      _builder.clearTeams()
    }
    /**
     * <code>string website = 8;</code>
     */
    var website: kotlin.String
      @JvmName("getWebsite")
      get() = _builder.getWebsite()
      @JvmName("setWebsite")
      set(value) {
        _builder.setWebsite(value)
      }
    /**
     * <code>string website = 8;</code>
     */
    fun clearWebsite() {
      _builder.clearWebsite()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Race.copy(block: io.github.patxibocos.pcsscraper.protobuf.race.RaceKt.Dsl.() -> Unit): io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Race =
  io.github.patxibocos.pcsscraper.protobuf.race.RaceKt.Dsl._create(this.toBuilder()).apply { block() }._build()
