//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/proto/race.proto

package io.github.patxibocos.pcsscraper.protobuf.race;

@kotlin.jvm.JvmSynthetic
inline fun stage(block: io.github.patxibocos.pcsscraper.protobuf.race.StageKt.Dsl.() -> Unit): io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage =
  io.github.patxibocos.pcsscraper.protobuf.race.StageKt.Dsl._create(io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage.newBuilder()).apply { block() }._build()
object StageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage = _builder.build()

    /**
     * <code>string id = 1;</code>
     */
    var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>string id = 1;</code>
     */
    fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>.google.protobuf.Timestamp start_date = 2;</code>
     */
    var startDate: com.google.protobuf.Timestamp
      @JvmName("getStartDate")
      get() = _builder.getStartDate()
      @JvmName("setStartDate")
      set(value) {
        _builder.setStartDate(value)
      }
    /**
     * <code>.google.protobuf.Timestamp start_date = 2;</code>
     */
    fun clearStartDate() {
      _builder.clearStartDate()
    }
    /**
     * <code>.google.protobuf.Timestamp start_date = 2;</code>
     * @return Whether the startDate field is set.
     */
    fun hasStartDate(): kotlin.Boolean {
      return _builder.hasStartDate()
    }

    /**
     * <code>float distance = 3;</code>
     */
    var distance: kotlin.Float
      @JvmName("getDistance")
      get() = _builder.getDistance()
      @JvmName("setDistance")
      set(value) {
        _builder.setDistance(value)
      }
    /**
     * <code>float distance = 3;</code>
     */
    fun clearDistance() {
      _builder.clearDistance()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class ResultProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.RiderResult result = 4;</code>
     */
     val result: com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderResult, ResultProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getResultList()
      )
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.RiderResult result = 4;</code>
     * @param value The result to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addResult")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderResult, ResultProxy>.add(value: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderResult) {
      _builder.addResult(value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.RiderResult result = 4;</code>
     * @param value The result to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignResult")
    inline operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderResult, ResultProxy>.plusAssign(value: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderResult) {
      add(value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.RiderResult result = 4;</code>
     * @param values The result to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllResult")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderResult, ResultProxy>.addAll(values: kotlin.collections.Iterable<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderResult>) {
      _builder.addAllResult(values)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.RiderResult result = 4;</code>
     * @param values The result to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllResult")
    inline operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderResult, ResultProxy>.plusAssign(values: kotlin.collections.Iterable<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderResult>) {
      addAll(values)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.RiderResult result = 4;</code>
     * @param index The index to set the value at.
     * @param value The result to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setResult")
    operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderResult, ResultProxy>.set(index: kotlin.Int, value: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderResult) {
      _builder.setResult(index, value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.RiderResult result = 4;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearResult")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderResult, ResultProxy>.clear() {
      _builder.clearResult()
    }
    /**
     * <code>.io.github.patxibocos.pcsscraper.protobuf.race.Stage.Type type = 5;</code>
     */
    var type: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage.Type
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * <code>.io.github.patxibocos.pcsscraper.protobuf.race.Stage.Type type = 5;</code>
     */
    fun clearType() {
      _builder.clearType()
    }

    /**
     * <code>optional string departure = 6;</code>
     */
    var departure: kotlin.String
      @JvmName("getDeparture")
      get() = _builder.getDeparture()
      @JvmName("setDeparture")
      set(value) {
        _builder.setDeparture(value)
      }
    /**
     * <code>optional string departure = 6;</code>
     */
    fun clearDeparture() {
      _builder.clearDeparture()
    }
    /**
     * <code>optional string departure = 6;</code>
     * @return Whether the departure field is set.
     */
    fun hasDeparture(): kotlin.Boolean {
      return _builder.hasDeparture()
    }

    /**
     * <code>optional string arrival = 7;</code>
     */
    var arrival: kotlin.String
      @JvmName("getArrival")
      get() = _builder.getArrival()
      @JvmName("setArrival")
      set(value) {
        _builder.setArrival(value)
      }
    /**
     * <code>optional string arrival = 7;</code>
     */
    fun clearArrival() {
      _builder.clearArrival()
    }
    /**
     * <code>optional string arrival = 7;</code>
     * @return Whether the arrival field is set.
     */
    fun hasArrival(): kotlin.Boolean {
      return _builder.hasArrival()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage.copy(block: io.github.patxibocos.pcsscraper.protobuf.race.StageKt.Dsl.() -> Unit): io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.Stage =
  io.github.patxibocos.pcsscraper.protobuf.race.StageKt.Dsl._create(this.toBuilder()).apply { block() }._build()
