//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/proto/race.proto

package io.github.patxibocos.pcsscraper.protobuf.race;

@kotlin.jvm.JvmSynthetic
inline fun teamParticipation(block: io.github.patxibocos.pcsscraper.protobuf.race.TeamParticipationKt.Dsl.() -> Unit): io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation =
  io.github.patxibocos.pcsscraper.protobuf.race.TeamParticipationKt.Dsl._create(io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation.newBuilder()).apply { block() }._build()
object TeamParticipationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation = _builder.build()

    /**
     * <code>string team_id = 1;</code>
     */
    var teamId: kotlin.String
      @JvmName("getTeamId")
      get() = _builder.getTeamId()
      @JvmName("setTeamId")
      set(value) {
        _builder.setTeamId(value)
      }
    /**
     * <code>string team_id = 1;</code>
     */
    fun clearTeamId() {
      _builder.clearTeamId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class RidersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.RiderParticipation riders = 2;</code>
     */
     val riders: com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderParticipation, RidersProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getRidersList()
      )
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.RiderParticipation riders = 2;</code>
     * @param value The riders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRiders")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderParticipation, RidersProxy>.add(value: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderParticipation) {
      _builder.addRiders(value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.RiderParticipation riders = 2;</code>
     * @param value The riders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRiders")
    inline operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderParticipation, RidersProxy>.plusAssign(value: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderParticipation) {
      add(value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.RiderParticipation riders = 2;</code>
     * @param values The riders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRiders")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderParticipation, RidersProxy>.addAll(values: kotlin.collections.Iterable<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderParticipation>) {
      _builder.addAllRiders(values)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.RiderParticipation riders = 2;</code>
     * @param values The riders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRiders")
    inline operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderParticipation, RidersProxy>.plusAssign(values: kotlin.collections.Iterable<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderParticipation>) {
      addAll(values)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.RiderParticipation riders = 2;</code>
     * @param index The index to set the value at.
     * @param value The riders to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRiders")
    operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderParticipation, RidersProxy>.set(index: kotlin.Int, value: io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderParticipation) {
      _builder.setRiders(index, value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.race.RiderParticipation riders = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRiders")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.RiderParticipation, RidersProxy>.clear() {
      _builder.clearRiders()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation.copy(block: io.github.patxibocos.pcsscraper.protobuf.race.TeamParticipationKt.Dsl.() -> Unit): io.github.patxibocos.pcsscraper.protobuf.race.RaceOuterClass.TeamParticipation =
  io.github.patxibocos.pcsscraper.protobuf.race.TeamParticipationKt.Dsl._create(this.toBuilder()).apply { block() }._build()
