[versions]
exposed = "0.41.1"
kotest = "5.6.2"
kotlin = "1.8.22"
ktlint = "0.48.1"
ktor = "2.3.1"
log4j = "2.20.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version = "6.19.0" }
google-protobuf = { id = "com.google.protobuf", version = "0.9.3" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }

[libraries]
aws-s3 = "com.amazonaws:aws-java-sdk-s3:1.12.484"
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
firebase-admin = "com.google.firebase:firebase-admin:9.1.1"
kotlin-cli = "org.jetbrains.kotlinx:kotlinx-cli-jvm:0.3.5"
kotlin-logging = "io.github.microutils:kotlin-logging-jvm:3.0.5"
kotlin-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1"
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
log4j-api-kotlin = "org.apache.logging.log4j:log4j-api-kotlin:1.2.0"
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
protobuf-kotlin = "com.google.protobuf:protobuf-kotlin:3.23.2"
skrapeit = "it.skrape:skrapeit:1.2.2"
sqlite-jdbc = "org.xerial:sqlite-jdbc:3.42.0.0"

test-kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
test-kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
test-mockk = "io.mockk:mockk:1.13.5"
