[versions]
exposed = "0.32.1"
ktlint = "0.42.1"

[libraries]
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
kotlin-cli = "org.jetbrains.kotlinx:kotlinx-cli-jvm:0.3.2"
kotlin-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.2"
ktor-client-core = "io.ktor:ktor-client-core:1.6.2"
ktor-client-cio = "io.ktor:ktor-client-cio:1.6.2"
skrapeit = "it.skrape:skrapeit:1.1.5"
sqlite-jdbc = "org.xerial:sqlite-jdbc:3.36.0.1"