[versions]
exposed = "0.33.1"
kotest = "4.6.2"
ktlint = "0.42.1"
ktor = "1.6.2"

[libraries]
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
firebase-admin = "com.google.firebase:firebase-admin:8.0.1"
kotlin-cli = "org.jetbrains.kotlinx:kotlinx-cli-jvm:0.3.2"
kotlin-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.2"
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
protobuf-kotlin = "com.google.protobuf:protobuf-kotlin:3.18.0-rc-2"
skrapeit = "it.skrape:skrapeit:1.1.5"
sqlite-jdbc = "org.xerial:sqlite-jdbc:3.36.0.1"

test-kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
test-kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
test-mockk = "io.mockk:mockk:1.12.0"
