[versions]
exposed = "0.33.1"
ktlint = "0.42.1"
ktor = "1.6.2"

[libraries]
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
kotlin-cli = "org.jetbrains.kotlinx:kotlinx-cli-jvm:0.3.2"
kotlin-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.2"
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
skrapeit = "it.skrape:skrapeit:1.1.5"
sqlite-jdbc = "org.xerial:sqlite-jdbc:3.36.0.1"