[versions]
exposed = "0.38.2"
kotest = "5.3.1"
ktlint = "0.45.2"
ktor = "2.0.2"
log4j = "2.17.2"

[libraries]
aws-s3 = "com.amazonaws:aws-java-sdk-s3:1.12.236"
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
firebase-admin = "com.google.firebase:firebase-admin:8.2.0"
kotlin-cli = "org.jetbrains.kotlinx:kotlinx-cli-jvm:0.3.4"
kotlin-logging = "io.github.microutils:kotlin-logging-jvm:2.1.20"
kotlin-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.3"
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }
protobuf-kotlin = "com.google.protobuf:protobuf-kotlin:3.21.1"
skrapeit = "it.skrape:skrapeit:1.2.1"
sqlite-jdbc = "org.xerial:sqlite-jdbc:3.36.0.3"

test-kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
test-kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
test-mockk = "io.mockk:mockk:1.12.2"
