[versions]
exposed = "0.40.1"
kotest = "5.5.0"
ktlint = "0.47.1"
ktor = "2.1.2"
log4j = "2.19.0"

[libraries]
aws-s3 = "com.amazonaws:aws-java-sdk-s3:1.12.316"
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
firebase-admin = "com.google.firebase:firebase-admin:9.0.0"
kotlin-cli = "org.jetbrains.kotlinx:kotlinx-cli-jvm:0.3.5"
kotlin-logging = "io.github.microutils:kotlin-logging-jvm:3.0.0"
kotlin-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.0"
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }
protobuf-kotlin = "com.google.protobuf:protobuf-kotlin:3.21.7"
skrapeit = "it.skrape:skrapeit:1.2.2"
sqlite-jdbc = "org.xerial:sqlite-jdbc:3.39.3.0"

test-kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
test-kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
test-mockk = "io.mockk:mockk:1.13.2"
