// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/races.proto

package io.github.patxibocos.pcsscraper.protobuf;

public final class RacesOuterClass {
  private RacesOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RacesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.github.patxibocos.pcsscraper.protobuf.Races)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
     */
    java.util.List<io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race> 
        getRacesList();
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
     */
    io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race getRaces(int index);
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
     */
    int getRacesCount();
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
     */
    java.util.List<? extends io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RaceOrBuilder> 
        getRacesOrBuilderList();
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
     */
    io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RaceOrBuilder getRacesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code io.github.patxibocos.pcsscraper.protobuf.Races}
   */
  public static final class Races extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.github.patxibocos.pcsscraper.protobuf.Races)
      RacesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Races.newBuilder() to construct.
    private Races(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Races() {
      races_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Races();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Races(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                races_ = new java.util.ArrayList<io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race>();
                mutable_bitField0_ |= 0x00000001;
              }
              races_.add(
                  input.readMessage(io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          races_ = java.util.Collections.unmodifiableList(races_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_Races_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_Races_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races.class, io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races.Builder.class);
    }

    public static final int RACES_FIELD_NUMBER = 1;
    private java.util.List<io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race> races_;
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
     */
    @java.lang.Override
    public java.util.List<io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race> getRacesList() {
      return races_;
    }
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RaceOrBuilder> 
        getRacesOrBuilderList() {
      return races_;
    }
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
     */
    @java.lang.Override
    public int getRacesCount() {
      return races_.size();
    }
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
     */
    @java.lang.Override
    public io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race getRaces(int index) {
      return races_.get(index);
    }
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
     */
    @java.lang.Override
    public io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RaceOrBuilder getRacesOrBuilder(
        int index) {
      return races_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < races_.size(); i++) {
        output.writeMessage(1, races_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < races_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, races_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races)) {
        return super.equals(obj);
      }
      io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races other = (io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races) obj;

      if (!getRacesList()
          .equals(other.getRacesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRacesCount() > 0) {
        hash = (37 * hash) + RACES_FIELD_NUMBER;
        hash = (53 * hash) + getRacesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.github.patxibocos.pcsscraper.protobuf.Races}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.github.patxibocos.pcsscraper.protobuf.Races)
        io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.RacesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_Races_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_Races_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races.class, io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races.Builder.class);
      }

      // Construct using io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRacesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (racesBuilder_ == null) {
          races_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          racesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_Races_descriptor;
      }

      @java.lang.Override
      public io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races getDefaultInstanceForType() {
        return io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races build() {
        io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races buildPartial() {
        io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races result = new io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races(this);
        int from_bitField0_ = bitField0_;
        if (racesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            races_ = java.util.Collections.unmodifiableList(races_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.races_ = races_;
        } else {
          result.races_ = racesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races) {
          return mergeFrom((io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races other) {
        if (other == io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races.getDefaultInstance()) return this;
        if (racesBuilder_ == null) {
          if (!other.races_.isEmpty()) {
            if (races_.isEmpty()) {
              races_ = other.races_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRacesIsMutable();
              races_.addAll(other.races_);
            }
            onChanged();
          }
        } else {
          if (!other.races_.isEmpty()) {
            if (racesBuilder_.isEmpty()) {
              racesBuilder_.dispose();
              racesBuilder_ = null;
              races_ = other.races_;
              bitField0_ = (bitField0_ & ~0x00000001);
              racesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRacesFieldBuilder() : null;
            } else {
              racesBuilder_.addAllMessages(other.races_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race> races_ =
        java.util.Collections.emptyList();
      private void ensureRacesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          races_ = new java.util.ArrayList<io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race>(races_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race, io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race.Builder, io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RaceOrBuilder> racesBuilder_;

      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public java.util.List<io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race> getRacesList() {
        if (racesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(races_);
        } else {
          return racesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public int getRacesCount() {
        if (racesBuilder_ == null) {
          return races_.size();
        } else {
          return racesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race getRaces(int index) {
        if (racesBuilder_ == null) {
          return races_.get(index);
        } else {
          return racesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public Builder setRaces(
          int index, io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race value) {
        if (racesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRacesIsMutable();
          races_.set(index, value);
          onChanged();
        } else {
          racesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public Builder setRaces(
          int index, io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race.Builder builderForValue) {
        if (racesBuilder_ == null) {
          ensureRacesIsMutable();
          races_.set(index, builderForValue.build());
          onChanged();
        } else {
          racesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public Builder addRaces(io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race value) {
        if (racesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRacesIsMutable();
          races_.add(value);
          onChanged();
        } else {
          racesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public Builder addRaces(
          int index, io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race value) {
        if (racesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRacesIsMutable();
          races_.add(index, value);
          onChanged();
        } else {
          racesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public Builder addRaces(
          io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race.Builder builderForValue) {
        if (racesBuilder_ == null) {
          ensureRacesIsMutable();
          races_.add(builderForValue.build());
          onChanged();
        } else {
          racesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public Builder addRaces(
          int index, io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race.Builder builderForValue) {
        if (racesBuilder_ == null) {
          ensureRacesIsMutable();
          races_.add(index, builderForValue.build());
          onChanged();
        } else {
          racesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public Builder addAllRaces(
          java.lang.Iterable<? extends io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race> values) {
        if (racesBuilder_ == null) {
          ensureRacesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, races_);
          onChanged();
        } else {
          racesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public Builder clearRaces() {
        if (racesBuilder_ == null) {
          races_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          racesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public Builder removeRaces(int index) {
        if (racesBuilder_ == null) {
          ensureRacesIsMutable();
          races_.remove(index);
          onChanged();
        } else {
          racesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race.Builder getRacesBuilder(
          int index) {
        return getRacesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RaceOrBuilder getRacesOrBuilder(
          int index) {
        if (racesBuilder_ == null) {
          return races_.get(index);  } else {
          return racesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public java.util.List<? extends io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RaceOrBuilder> 
           getRacesOrBuilderList() {
        if (racesBuilder_ != null) {
          return racesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(races_);
        }
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race.Builder addRacesBuilder() {
        return getRacesFieldBuilder().addBuilder(
            io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race.getDefaultInstance());
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race.Builder addRacesBuilder(
          int index) {
        return getRacesFieldBuilder().addBuilder(
            index, io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race.getDefaultInstance());
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 1;</code>
       */
      public java.util.List<io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race.Builder> 
           getRacesBuilderList() {
        return getRacesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race, io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race.Builder, io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RaceOrBuilder> 
          getRacesFieldBuilder() {
        if (racesBuilder_ == null) {
          racesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race, io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race.Builder, io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RaceOrBuilder>(
                  races_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          races_ = null;
        }
        return racesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.github.patxibocos.pcsscraper.protobuf.Races)
    }

    // @@protoc_insertion_point(class_scope:io.github.patxibocos.pcsscraper.protobuf.Races)
    private static final io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races();
    }

    public static io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Races>
        PARSER = new com.google.protobuf.AbstractParser<Races>() {
      @java.lang.Override
      public Races parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Races(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Races> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Races> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.patxibocos.pcsscraper.protobuf.RacesOuterClass.Races getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_patxibocos_pcsscraper_protobuf_Races_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_patxibocos_pcsscraper_protobuf_Races_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032src/main/proto/races.proto\022(io.github." +
      "patxibocos.pcsscraper.protobuf\032\031src/main" +
      "/proto/race.proto\"F\n\005Races\022=\n\005races\030\001 \003(" +
      "\0132..io.github.patxibocos.pcsscraper.prot" +
      "obuf.RaceB\"Z github.com/patxibocos/pcssc" +
      "raperb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.getDescriptor(),
        });
    internal_static_io_github_patxibocos_pcsscraper_protobuf_Races_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_github_patxibocos_pcsscraper_protobuf_Races_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_patxibocos_pcsscraper_protobuf_Races_descriptor,
        new java.lang.String[] { "Races", });
    io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
