// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: team.proto

package io.github.patxibocos.pcsscraper.protobuf;

public final class TeamOuterClass {
  private TeamOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TeamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.github.patxibocos.pcsscraper.protobuf.Teams)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
     */
    java.util.List<io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team> 
        getTeamsList();
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
     */
    io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team getTeams(int index);
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
     */
    int getTeamsCount();
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
     */
    java.util.List<? extends io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.TeamOrBuilder> 
        getTeamsOrBuilderList();
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
     */
    io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.TeamOrBuilder getTeamsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code io.github.patxibocos.pcsscraper.protobuf.Teams}
   */
  public static final class Teams extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.github.patxibocos.pcsscraper.protobuf.Teams)
      TeamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Teams.newBuilder() to construct.
    private Teams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Teams() {
      teams_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Teams();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Teams(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                teams_ = new java.util.ArrayList<io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team>();
                mutable_bitField0_ |= 0x00000001;
              }
              teams_.add(
                  input.readMessage(io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          teams_ = java.util.Collections.unmodifiableList(teams_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_Teams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_Teams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams.class, io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams.Builder.class);
    }

    public static final int TEAMS_FIELD_NUMBER = 1;
    private java.util.List<io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team> teams_;
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
     */
    @java.lang.Override
    public java.util.List<io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team> getTeamsList() {
      return teams_;
    }
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.TeamOrBuilder> 
        getTeamsOrBuilderList() {
      return teams_;
    }
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
     */
    @java.lang.Override
    public int getTeamsCount() {
      return teams_.size();
    }
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
     */
    @java.lang.Override
    public io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team getTeams(int index) {
      return teams_.get(index);
    }
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
     */
    @java.lang.Override
    public io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.TeamOrBuilder getTeamsOrBuilder(
        int index) {
      return teams_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < teams_.size(); i++) {
        output.writeMessage(1, teams_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < teams_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, teams_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams)) {
        return super.equals(obj);
      }
      io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams other = (io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams) obj;

      if (!getTeamsList()
          .equals(other.getTeamsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTeamsCount() > 0) {
        hash = (37 * hash) + TEAMS_FIELD_NUMBER;
        hash = (53 * hash) + getTeamsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.github.patxibocos.pcsscraper.protobuf.Teams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.github.patxibocos.pcsscraper.protobuf.Teams)
        io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.TeamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_Teams_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_Teams_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams.class, io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams.Builder.class);
      }

      // Construct using io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTeamsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (teamsBuilder_ == null) {
          teams_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          teamsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_Teams_descriptor;
      }

      @java.lang.Override
      public io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams getDefaultInstanceForType() {
        return io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams build() {
        io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams buildPartial() {
        io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams result = new io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams(this);
        int from_bitField0_ = bitField0_;
        if (teamsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            teams_ = java.util.Collections.unmodifiableList(teams_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.teams_ = teams_;
        } else {
          result.teams_ = teamsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams) {
          return mergeFrom((io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams other) {
        if (other == io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams.getDefaultInstance()) return this;
        if (teamsBuilder_ == null) {
          if (!other.teams_.isEmpty()) {
            if (teams_.isEmpty()) {
              teams_ = other.teams_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTeamsIsMutable();
              teams_.addAll(other.teams_);
            }
            onChanged();
          }
        } else {
          if (!other.teams_.isEmpty()) {
            if (teamsBuilder_.isEmpty()) {
              teamsBuilder_.dispose();
              teamsBuilder_ = null;
              teams_ = other.teams_;
              bitField0_ = (bitField0_ & ~0x00000001);
              teamsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTeamsFieldBuilder() : null;
            } else {
              teamsBuilder_.addAllMessages(other.teams_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team> teams_ =
        java.util.Collections.emptyList();
      private void ensureTeamsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          teams_ = new java.util.ArrayList<io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team>(teams_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team, io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Builder, io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.TeamOrBuilder> teamsBuilder_;

      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public java.util.List<io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team> getTeamsList() {
        if (teamsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(teams_);
        } else {
          return teamsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public int getTeamsCount() {
        if (teamsBuilder_ == null) {
          return teams_.size();
        } else {
          return teamsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team getTeams(int index) {
        if (teamsBuilder_ == null) {
          return teams_.get(index);
        } else {
          return teamsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public Builder setTeams(
          int index, io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team value) {
        if (teamsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeamsIsMutable();
          teams_.set(index, value);
          onChanged();
        } else {
          teamsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public Builder setTeams(
          int index, io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Builder builderForValue) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          teams_.set(index, builderForValue.build());
          onChanged();
        } else {
          teamsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public Builder addTeams(io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team value) {
        if (teamsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeamsIsMutable();
          teams_.add(value);
          onChanged();
        } else {
          teamsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public Builder addTeams(
          int index, io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team value) {
        if (teamsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeamsIsMutable();
          teams_.add(index, value);
          onChanged();
        } else {
          teamsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public Builder addTeams(
          io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Builder builderForValue) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          teams_.add(builderForValue.build());
          onChanged();
        } else {
          teamsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public Builder addTeams(
          int index, io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Builder builderForValue) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          teams_.add(index, builderForValue.build());
          onChanged();
        } else {
          teamsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public Builder addAllTeams(
          java.lang.Iterable<? extends io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team> values) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, teams_);
          onChanged();
        } else {
          teamsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public Builder clearTeams() {
        if (teamsBuilder_ == null) {
          teams_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          teamsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public Builder removeTeams(int index) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          teams_.remove(index);
          onChanged();
        } else {
          teamsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Builder getTeamsBuilder(
          int index) {
        return getTeamsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.TeamOrBuilder getTeamsOrBuilder(
          int index) {
        if (teamsBuilder_ == null) {
          return teams_.get(index);  } else {
          return teamsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public java.util.List<? extends io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.TeamOrBuilder> 
           getTeamsOrBuilderList() {
        if (teamsBuilder_ != null) {
          return teamsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(teams_);
        }
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Builder addTeamsBuilder() {
        return getTeamsFieldBuilder().addBuilder(
            io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.getDefaultInstance());
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Builder addTeamsBuilder(
          int index) {
        return getTeamsFieldBuilder().addBuilder(
            index, io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.getDefaultInstance());
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
       */
      public java.util.List<io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Builder> 
           getTeamsBuilderList() {
        return getTeamsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team, io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Builder, io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.TeamOrBuilder> 
          getTeamsFieldBuilder() {
        if (teamsBuilder_ == null) {
          teamsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team, io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Builder, io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.TeamOrBuilder>(
                  teams_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          teams_ = null;
        }
        return teamsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.github.patxibocos.pcsscraper.protobuf.Teams)
    }

    // @@protoc_insertion_point(class_scope:io.github.patxibocos.pcsscraper.protobuf.Teams)
    private static final io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams();
    }

    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Teams>
        PARSER = new com.google.protobuf.AbstractParser<Teams>() {
      @java.lang.Override
      public Teams parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Teams(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Teams> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Teams> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Teams getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TeamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.github.patxibocos.pcsscraper.protobuf.Team)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.io.github.patxibocos.pcsscraper.protobuf.Team.Status status = 3;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.io.github.patxibocos.pcsscraper.protobuf.Team.Status status = 3;</code>
     * @return The status.
     */
    io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Status getStatus();

    /**
     * <code>string abbreviation = 4;</code>
     * @return The abbreviation.
     */
    java.lang.String getAbbreviation();
    /**
     * <code>string abbreviation = 4;</code>
     * @return The bytes for abbreviation.
     */
    com.google.protobuf.ByteString
        getAbbreviationBytes();

    /**
     * <code>string country = 5;</code>
     * @return The country.
     */
    java.lang.String getCountry();
    /**
     * <code>string country = 5;</code>
     * @return The bytes for country.
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <code>string bike = 6;</code>
     * @return The bike.
     */
    java.lang.String getBike();
    /**
     * <code>string bike = 6;</code>
     * @return The bytes for bike.
     */
    com.google.protobuf.ByteString
        getBikeBytes();

    /**
     * <code>string jersey = 7;</code>
     * @return The jersey.
     */
    java.lang.String getJersey();
    /**
     * <code>string jersey = 7;</code>
     * @return The bytes for jersey.
     */
    com.google.protobuf.ByteString
        getJerseyBytes();

    /**
     * <code>uint32 year = 8;</code>
     * @return The year.
     */
    int getYear();

    /**
     * <code>repeated string rider_ids = 9;</code>
     * @return A list containing the riderIds.
     */
    java.util.List<java.lang.String>
        getRiderIdsList();
    /**
     * <code>repeated string rider_ids = 9;</code>
     * @return The count of riderIds.
     */
    int getRiderIdsCount();
    /**
     * <code>repeated string rider_ids = 9;</code>
     * @param index The index of the element to return.
     * @return The riderIds at the given index.
     */
    java.lang.String getRiderIds(int index);
    /**
     * <code>repeated string rider_ids = 9;</code>
     * @param index The index of the value to return.
     * @return The bytes of the riderIds at the given index.
     */
    com.google.protobuf.ByteString
        getRiderIdsBytes(int index);

    /**
     * <code>optional string website = 10;</code>
     * @return Whether the website field is set.
     */
    boolean hasWebsite();
    /**
     * <code>optional string website = 10;</code>
     * @return The website.
     */
    java.lang.String getWebsite();
    /**
     * <code>optional string website = 10;</code>
     * @return The bytes for website.
     */
    com.google.protobuf.ByteString
        getWebsiteBytes();
  }
  /**
   * Protobuf type {@code io.github.patxibocos.pcsscraper.protobuf.Team}
   */
  public static final class Team extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.github.patxibocos.pcsscraper.protobuf.Team)
      TeamOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Team.newBuilder() to construct.
    private Team(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Team() {
      id_ = "";
      name_ = "";
      status_ = 0;
      abbreviation_ = "";
      country_ = "";
      bike_ = "";
      jersey_ = "";
      riderIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      website_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Team();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Team(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              abbreviation_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              country_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              bike_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              jersey_ = s;
              break;
            }
            case 64: {

              year_ = input.readUInt32();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                riderIds_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              riderIds_.add(s);
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              website_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          riderIds_ = riderIds_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_Team_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_Team_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.class, io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Builder.class);
    }

    /**
     * Protobuf enum {@code io.github.patxibocos.pcsscraper.protobuf.Team.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>STATUS_UNSPECIFIED = 0;</code>
       */
      STATUS_UNSPECIFIED(0),
      /**
       * <code>STATUS_WORLD_TEAM = 1;</code>
       */
      STATUS_WORLD_TEAM(1),
      /**
       * <code>STATUS_PRO_TEAM = 2;</code>
       */
      STATUS_PRO_TEAM(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>STATUS_UNSPECIFIED = 0;</code>
       */
      public static final int STATUS_UNSPECIFIED_VALUE = 0;
      /**
       * <code>STATUS_WORLD_TEAM = 1;</code>
       */
      public static final int STATUS_WORLD_TEAM_VALUE = 1;
      /**
       * <code>STATUS_PRO_TEAM = 2;</code>
       */
      public static final int STATUS_PRO_TEAM_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Status forNumber(int value) {
        switch (value) {
          case 0: return STATUS_UNSPECIFIED;
          case 1: return STATUS_WORLD_TEAM;
          case 2: return STATUS_PRO_TEAM;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:io.github.patxibocos.pcsscraper.protobuf.Team.Status)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <code>.io.github.patxibocos.pcsscraper.protobuf.Team.Status status = 3;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.io.github.patxibocos.pcsscraper.protobuf.Team.Status status = 3;</code>
     * @return The status.
     */
    @java.lang.Override public io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Status getStatus() {
      @SuppressWarnings("deprecation")
      io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Status result = io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Status.valueOf(status_);
      return result == null ? io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Status.UNRECOGNIZED : result;
    }

    public static final int ABBREVIATION_FIELD_NUMBER = 4;
    private volatile java.lang.Object abbreviation_;
    /**
     * <code>string abbreviation = 4;</code>
     * @return The abbreviation.
     */
    @java.lang.Override
    public java.lang.String getAbbreviation() {
      java.lang.Object ref = abbreviation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        abbreviation_ = s;
        return s;
      }
    }
    /**
     * <code>string abbreviation = 4;</code>
     * @return The bytes for abbreviation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAbbreviationBytes() {
      java.lang.Object ref = abbreviation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        abbreviation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRY_FIELD_NUMBER = 5;
    private volatile java.lang.Object country_;
    /**
     * <code>string country = 5;</code>
     * @return The country.
     */
    @java.lang.Override
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      }
    }
    /**
     * <code>string country = 5;</code>
     * @return The bytes for country.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIKE_FIELD_NUMBER = 6;
    private volatile java.lang.Object bike_;
    /**
     * <code>string bike = 6;</code>
     * @return The bike.
     */
    @java.lang.Override
    public java.lang.String getBike() {
      java.lang.Object ref = bike_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bike_ = s;
        return s;
      }
    }
    /**
     * <code>string bike = 6;</code>
     * @return The bytes for bike.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBikeBytes() {
      java.lang.Object ref = bike_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bike_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JERSEY_FIELD_NUMBER = 7;
    private volatile java.lang.Object jersey_;
    /**
     * <code>string jersey = 7;</code>
     * @return The jersey.
     */
    @java.lang.Override
    public java.lang.String getJersey() {
      java.lang.Object ref = jersey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jersey_ = s;
        return s;
      }
    }
    /**
     * <code>string jersey = 7;</code>
     * @return The bytes for jersey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJerseyBytes() {
      java.lang.Object ref = jersey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jersey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int YEAR_FIELD_NUMBER = 8;
    private int year_;
    /**
     * <code>uint32 year = 8;</code>
     * @return The year.
     */
    @java.lang.Override
    public int getYear() {
      return year_;
    }

    public static final int RIDER_IDS_FIELD_NUMBER = 9;
    private com.google.protobuf.LazyStringList riderIds_;
    /**
     * <code>repeated string rider_ids = 9;</code>
     * @return A list containing the riderIds.
     */
    public com.google.protobuf.ProtocolStringList
        getRiderIdsList() {
      return riderIds_;
    }
    /**
     * <code>repeated string rider_ids = 9;</code>
     * @return The count of riderIds.
     */
    public int getRiderIdsCount() {
      return riderIds_.size();
    }
    /**
     * <code>repeated string rider_ids = 9;</code>
     * @param index The index of the element to return.
     * @return The riderIds at the given index.
     */
    public java.lang.String getRiderIds(int index) {
      return riderIds_.get(index);
    }
    /**
     * <code>repeated string rider_ids = 9;</code>
     * @param index The index of the value to return.
     * @return The bytes of the riderIds at the given index.
     */
    public com.google.protobuf.ByteString
        getRiderIdsBytes(int index) {
      return riderIds_.getByteString(index);
    }

    public static final int WEBSITE_FIELD_NUMBER = 10;
    private volatile java.lang.Object website_;
    /**
     * <code>optional string website = 10;</code>
     * @return Whether the website field is set.
     */
    @java.lang.Override
    public boolean hasWebsite() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string website = 10;</code>
     * @return The website.
     */
    @java.lang.Override
    public java.lang.String getWebsite() {
      java.lang.Object ref = website_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        website_ = s;
        return s;
      }
    }
    /**
     * <code>optional string website = 10;</code>
     * @return The bytes for website.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWebsiteBytes() {
      java.lang.Object ref = website_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        website_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (status_ != io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Status.STATUS_UNSPECIFIED.getNumber()) {
        output.writeEnum(3, status_);
      }
      if (!getAbbreviationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, abbreviation_);
      }
      if (!getCountryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, country_);
      }
      if (!getBikeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, bike_);
      }
      if (!getJerseyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, jersey_);
      }
      if (year_ != 0) {
        output.writeUInt32(8, year_);
      }
      for (int i = 0; i < riderIds_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, riderIds_.getRaw(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, website_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (status_ != io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Status.STATUS_UNSPECIFIED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, status_);
      }
      if (!getAbbreviationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, abbreviation_);
      }
      if (!getCountryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, country_);
      }
      if (!getBikeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, bike_);
      }
      if (!getJerseyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, jersey_);
      }
      if (year_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, year_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < riderIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(riderIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRiderIdsList().size();
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, website_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team)) {
        return super.equals(obj);
      }
      io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team other = (io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (status_ != other.status_) return false;
      if (!getAbbreviation()
          .equals(other.getAbbreviation())) return false;
      if (!getCountry()
          .equals(other.getCountry())) return false;
      if (!getBike()
          .equals(other.getBike())) return false;
      if (!getJersey()
          .equals(other.getJersey())) return false;
      if (getYear()
          != other.getYear()) return false;
      if (!getRiderIdsList()
          .equals(other.getRiderIdsList())) return false;
      if (hasWebsite() != other.hasWebsite()) return false;
      if (hasWebsite()) {
        if (!getWebsite()
            .equals(other.getWebsite())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + ABBREVIATION_FIELD_NUMBER;
      hash = (53 * hash) + getAbbreviation().hashCode();
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry().hashCode();
      hash = (37 * hash) + BIKE_FIELD_NUMBER;
      hash = (53 * hash) + getBike().hashCode();
      hash = (37 * hash) + JERSEY_FIELD_NUMBER;
      hash = (53 * hash) + getJersey().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
      if (getRiderIdsCount() > 0) {
        hash = (37 * hash) + RIDER_IDS_FIELD_NUMBER;
        hash = (53 * hash) + getRiderIdsList().hashCode();
      }
      if (hasWebsite()) {
        hash = (37 * hash) + WEBSITE_FIELD_NUMBER;
        hash = (53 * hash) + getWebsite().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.github.patxibocos.pcsscraper.protobuf.Team}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.github.patxibocos.pcsscraper.protobuf.Team)
        io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.TeamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_Team_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_Team_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.class, io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Builder.class);
      }

      // Construct using io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        status_ = 0;

        abbreviation_ = "";

        country_ = "";

        bike_ = "";

        jersey_ = "";

        year_ = 0;

        riderIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        website_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_Team_descriptor;
      }

      @java.lang.Override
      public io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team getDefaultInstanceForType() {
        return io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team build() {
        io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team buildPartial() {
        io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team result = new io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        result.status_ = status_;
        result.abbreviation_ = abbreviation_;
        result.country_ = country_;
        result.bike_ = bike_;
        result.jersey_ = jersey_;
        result.year_ = year_;
        if (((bitField0_ & 0x00000001) != 0)) {
          riderIds_ = riderIds_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.riderIds_ = riderIds_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.website_ = website_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team) {
          return mergeFrom((io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team other) {
        if (other == io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getAbbreviation().isEmpty()) {
          abbreviation_ = other.abbreviation_;
          onChanged();
        }
        if (!other.getCountry().isEmpty()) {
          country_ = other.country_;
          onChanged();
        }
        if (!other.getBike().isEmpty()) {
          bike_ = other.bike_;
          onChanged();
        }
        if (!other.getJersey().isEmpty()) {
          jersey_ = other.jersey_;
          onChanged();
        }
        if (other.getYear() != 0) {
          setYear(other.getYear());
        }
        if (!other.riderIds_.isEmpty()) {
          if (riderIds_.isEmpty()) {
            riderIds_ = other.riderIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRiderIdsIsMutable();
            riderIds_.addAll(other.riderIds_);
          }
          onChanged();
        }
        if (other.hasWebsite()) {
          bitField0_ |= 0x00000002;
          website_ = other.website_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.io.github.patxibocos.pcsscraper.protobuf.Team.Status status = 3;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.io.github.patxibocos.pcsscraper.protobuf.Team.Status status = 3;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.io.github.patxibocos.pcsscraper.protobuf.Team.Status status = 3;</code>
       * @return The status.
       */
      @java.lang.Override
      public io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Status getStatus() {
        @SuppressWarnings("deprecation")
        io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Status result = io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Status.valueOf(status_);
        return result == null ? io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.io.github.patxibocos.pcsscraper.protobuf.Team.Status status = 3;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.io.github.patxibocos.pcsscraper.protobuf.Team.Status status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object abbreviation_ = "";
      /**
       * <code>string abbreviation = 4;</code>
       * @return The abbreviation.
       */
      public java.lang.String getAbbreviation() {
        java.lang.Object ref = abbreviation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          abbreviation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string abbreviation = 4;</code>
       * @return The bytes for abbreviation.
       */
      public com.google.protobuf.ByteString
          getAbbreviationBytes() {
        java.lang.Object ref = abbreviation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          abbreviation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string abbreviation = 4;</code>
       * @param value The abbreviation to set.
       * @return This builder for chaining.
       */
      public Builder setAbbreviation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        abbreviation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string abbreviation = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAbbreviation() {
        
        abbreviation_ = getDefaultInstance().getAbbreviation();
        onChanged();
        return this;
      }
      /**
       * <code>string abbreviation = 4;</code>
       * @param value The bytes for abbreviation to set.
       * @return This builder for chaining.
       */
      public Builder setAbbreviationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        abbreviation_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object country_ = "";
      /**
       * <code>string country = 5;</code>
       * @return The country.
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string country = 5;</code>
       * @return The bytes for country.
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string country = 5;</code>
       * @param value The country to set.
       * @return This builder for chaining.
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string country = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountry() {
        
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <code>string country = 5;</code>
       * @param value The bytes for country to set.
       * @return This builder for chaining.
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        country_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bike_ = "";
      /**
       * <code>string bike = 6;</code>
       * @return The bike.
       */
      public java.lang.String getBike() {
        java.lang.Object ref = bike_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bike_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string bike = 6;</code>
       * @return The bytes for bike.
       */
      public com.google.protobuf.ByteString
          getBikeBytes() {
        java.lang.Object ref = bike_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bike_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bike = 6;</code>
       * @param value The bike to set.
       * @return This builder for chaining.
       */
      public Builder setBike(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bike_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string bike = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBike() {
        
        bike_ = getDefaultInstance().getBike();
        onChanged();
        return this;
      }
      /**
       * <code>string bike = 6;</code>
       * @param value The bytes for bike to set.
       * @return This builder for chaining.
       */
      public Builder setBikeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bike_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object jersey_ = "";
      /**
       * <code>string jersey = 7;</code>
       * @return The jersey.
       */
      public java.lang.String getJersey() {
        java.lang.Object ref = jersey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jersey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string jersey = 7;</code>
       * @return The bytes for jersey.
       */
      public com.google.protobuf.ByteString
          getJerseyBytes() {
        java.lang.Object ref = jersey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jersey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string jersey = 7;</code>
       * @param value The jersey to set.
       * @return This builder for chaining.
       */
      public Builder setJersey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jersey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string jersey = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearJersey() {
        
        jersey_ = getDefaultInstance().getJersey();
        onChanged();
        return this;
      }
      /**
       * <code>string jersey = 7;</code>
       * @param value The bytes for jersey to set.
       * @return This builder for chaining.
       */
      public Builder setJerseyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jersey_ = value;
        onChanged();
        return this;
      }

      private int year_ ;
      /**
       * <code>uint32 year = 8;</code>
       * @return The year.
       */
      @java.lang.Override
      public int getYear() {
        return year_;
      }
      /**
       * <code>uint32 year = 8;</code>
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(int value) {
        
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 year = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearYear() {
        
        year_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList riderIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRiderIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          riderIds_ = new com.google.protobuf.LazyStringArrayList(riderIds_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string rider_ids = 9;</code>
       * @return A list containing the riderIds.
       */
      public com.google.protobuf.ProtocolStringList
          getRiderIdsList() {
        return riderIds_.getUnmodifiableView();
      }
      /**
       * <code>repeated string rider_ids = 9;</code>
       * @return The count of riderIds.
       */
      public int getRiderIdsCount() {
        return riderIds_.size();
      }
      /**
       * <code>repeated string rider_ids = 9;</code>
       * @param index The index of the element to return.
       * @return The riderIds at the given index.
       */
      public java.lang.String getRiderIds(int index) {
        return riderIds_.get(index);
      }
      /**
       * <code>repeated string rider_ids = 9;</code>
       * @param index The index of the value to return.
       * @return The bytes of the riderIds at the given index.
       */
      public com.google.protobuf.ByteString
          getRiderIdsBytes(int index) {
        return riderIds_.getByteString(index);
      }
      /**
       * <code>repeated string rider_ids = 9;</code>
       * @param index The index to set the value at.
       * @param value The riderIds to set.
       * @return This builder for chaining.
       */
      public Builder setRiderIds(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRiderIdsIsMutable();
        riderIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string rider_ids = 9;</code>
       * @param value The riderIds to add.
       * @return This builder for chaining.
       */
      public Builder addRiderIds(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRiderIdsIsMutable();
        riderIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string rider_ids = 9;</code>
       * @param values The riderIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllRiderIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureRiderIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, riderIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string rider_ids = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearRiderIds() {
        riderIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string rider_ids = 9;</code>
       * @param value The bytes of the riderIds to add.
       * @return This builder for chaining.
       */
      public Builder addRiderIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRiderIdsIsMutable();
        riderIds_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object website_ = "";
      /**
       * <code>optional string website = 10;</code>
       * @return Whether the website field is set.
       */
      public boolean hasWebsite() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string website = 10;</code>
       * @return The website.
       */
      public java.lang.String getWebsite() {
        java.lang.Object ref = website_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          website_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string website = 10;</code>
       * @return The bytes for website.
       */
      public com.google.protobuf.ByteString
          getWebsiteBytes() {
        java.lang.Object ref = website_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          website_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string website = 10;</code>
       * @param value The website to set.
       * @return This builder for chaining.
       */
      public Builder setWebsite(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        website_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string website = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearWebsite() {
        bitField0_ = (bitField0_ & ~0x00000002);
        website_ = getDefaultInstance().getWebsite();
        onChanged();
        return this;
      }
      /**
       * <code>optional string website = 10;</code>
       * @param value The bytes for website to set.
       * @return This builder for chaining.
       */
      public Builder setWebsiteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000002;
        website_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.github.patxibocos.pcsscraper.protobuf.Team)
    }

    // @@protoc_insertion_point(class_scope:io.github.patxibocos.pcsscraper.protobuf.Team)
    private static final io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team();
    }

    public static io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Team>
        PARSER = new com.google.protobuf.AbstractParser<Team>() {
      @java.lang.Override
      public Team parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Team(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Team> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Team> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_patxibocos_pcsscraper_protobuf_Teams_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_patxibocos_pcsscraper_protobuf_Teams_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_patxibocos_pcsscraper_protobuf_Team_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_patxibocos_pcsscraper_protobuf_Team_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nteam.proto\022(io.github.patxibocos.pcssc" +
      "raper.protobuf\"F\n\005Teams\022=\n\005teams\030\001 \003(\0132." +
      ".io.github.patxibocos.pcsscraper.protobu" +
      "f.Team\"\275\002\n\004Team\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(" +
      "\t\022E\n\006status\030\003 \001(\01625.io.github.patxibocos" +
      ".pcsscraper.protobuf.Team.Status\022\024\n\014abbr" +
      "eviation\030\004 \001(\t\022\017\n\007country\030\005 \001(\t\022\014\n\004bike\030" +
      "\006 \001(\t\022\016\n\006jersey\030\007 \001(\t\022\014\n\004year\030\010 \001(\r\022\021\n\tr" +
      "ider_ids\030\t \003(\t\022\024\n\007website\030\n \001(\tH\000\210\001\001\"L\n\006" +
      "Status\022\026\n\022STATUS_UNSPECIFIED\020\000\022\025\n\021STATUS" +
      "_WORLD_TEAM\020\001\022\023\n\017STATUS_PRO_TEAM\020\002B\n\n\010_w" +
      "ebsiteB\"Z github.com/patxibocos/pcsscrap" +
      "erb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_github_patxibocos_pcsscraper_protobuf_Teams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_github_patxibocos_pcsscraper_protobuf_Teams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_patxibocos_pcsscraper_protobuf_Teams_descriptor,
        new java.lang.String[] { "Teams", });
    internal_static_io_github_patxibocos_pcsscraper_protobuf_Team_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_github_patxibocos_pcsscraper_protobuf_Team_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_patxibocos_pcsscraper_protobuf_Team_descriptor,
        new java.lang.String[] { "Id", "Name", "Status", "Abbreviation", "Country", "Bike", "Jersey", "Year", "RiderIds", "Website", "Website", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
