// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/rider.proto

package io.github.patxibocos.pcsscraper.protobuf.rider;

public final class RiderOuterClass {
  private RiderOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RiderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.github.patxibocos.pcsscraper.protobuf.rider.Rider)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string last_name = 3;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string last_name = 3;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>string country = 4;</code>
     * @return The country.
     */
    java.lang.String getCountry();
    /**
     * <code>string country = 4;</code>
     * @return The bytes for country.
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <code>optional .google.protobuf.Timestamp birth_date = 5;</code>
     * @return Whether the birthDate field is set.
     */
    boolean hasBirthDate();
    /**
     * <code>optional .google.protobuf.Timestamp birth_date = 5;</code>
     * @return The birthDate.
     */
    com.google.protobuf.Timestamp getBirthDate();
    /**
     * <code>optional .google.protobuf.Timestamp birth_date = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getBirthDateOrBuilder();

    /**
     * <code>string photo = 6;</code>
     * @return The photo.
     */
    java.lang.String getPhoto();
    /**
     * <code>string photo = 6;</code>
     * @return The bytes for photo.
     */
    com.google.protobuf.ByteString
        getPhotoBytes();

    /**
     * <code>optional string website = 7;</code>
     * @return Whether the website field is set.
     */
    boolean hasWebsite();
    /**
     * <code>optional string website = 7;</code>
     * @return The website.
     */
    java.lang.String getWebsite();
    /**
     * <code>optional string website = 7;</code>
     * @return The bytes for website.
     */
    com.google.protobuf.ByteString
        getWebsiteBytes();

    /**
     * <code>optional string birth_place = 8;</code>
     * @return Whether the birthPlace field is set.
     */
    boolean hasBirthPlace();
    /**
     * <code>optional string birth_place = 8;</code>
     * @return The birthPlace.
     */
    java.lang.String getBirthPlace();
    /**
     * <code>optional string birth_place = 8;</code>
     * @return The bytes for birthPlace.
     */
    com.google.protobuf.ByteString
        getBirthPlaceBytes();

    /**
     * <code>optional uint32 weight = 9;</code>
     * @return Whether the weight field is set.
     */
    boolean hasWeight();
    /**
     * <code>optional uint32 weight = 9;</code>
     * @return The weight.
     */
    int getWeight();

    /**
     * <code>optional uint32 height = 10;</code>
     * @return Whether the height field is set.
     */
    boolean hasHeight();
    /**
     * <code>optional uint32 height = 10;</code>
     * @return The height.
     */
    int getHeight();
  }
  /**
   * Protobuf type {@code io.github.patxibocos.pcsscraper.protobuf.rider.Rider}
   */
  public static final class Rider extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.github.patxibocos.pcsscraper.protobuf.rider.Rider)
      RiderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Rider.newBuilder() to construct.
    private Rider(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Rider() {
      id_ = "";
      firstName_ = "";
      lastName_ = "";
      country_ = "";
      photo_ = "";
      website_ = "";
      birthPlace_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Rider();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Rider(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              country_ = s;
              break;
            }
            case 42: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = birthDate_.toBuilder();
              }
              birthDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(birthDate_);
                birthDate_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              photo_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              website_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              birthPlace_ = s;
              break;
            }
            case 72: {
              bitField0_ |= 0x00000008;
              weight_ = input.readUInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000010;
              height_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_rider_Rider_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_rider_Rider_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider.class, io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIRST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string last_name = 3;</code>
     * @return The lastName.
     */
    @java.lang.Override
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string last_name = 3;</code>
     * @return The bytes for lastName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNTRY_FIELD_NUMBER = 4;
    private volatile java.lang.Object country_;
    /**
     * <code>string country = 4;</code>
     * @return The country.
     */
    @java.lang.Override
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      }
    }
    /**
     * <code>string country = 4;</code>
     * @return The bytes for country.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIRTH_DATE_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp birthDate_;
    /**
     * <code>optional .google.protobuf.Timestamp birth_date = 5;</code>
     * @return Whether the birthDate field is set.
     */
    @java.lang.Override
    public boolean hasBirthDate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .google.protobuf.Timestamp birth_date = 5;</code>
     * @return The birthDate.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getBirthDate() {
      return birthDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthDate_;
    }
    /**
     * <code>optional .google.protobuf.Timestamp birth_date = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getBirthDateOrBuilder() {
      return birthDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthDate_;
    }

    public static final int PHOTO_FIELD_NUMBER = 6;
    private volatile java.lang.Object photo_;
    /**
     * <code>string photo = 6;</code>
     * @return The photo.
     */
    @java.lang.Override
    public java.lang.String getPhoto() {
      java.lang.Object ref = photo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        photo_ = s;
        return s;
      }
    }
    /**
     * <code>string photo = 6;</code>
     * @return The bytes for photo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhotoBytes() {
      java.lang.Object ref = photo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        photo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEBSITE_FIELD_NUMBER = 7;
    private volatile java.lang.Object website_;
    /**
     * <code>optional string website = 7;</code>
     * @return Whether the website field is set.
     */
    @java.lang.Override
    public boolean hasWebsite() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string website = 7;</code>
     * @return The website.
     */
    @java.lang.Override
    public java.lang.String getWebsite() {
      java.lang.Object ref = website_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        website_ = s;
        return s;
      }
    }
    /**
     * <code>optional string website = 7;</code>
     * @return The bytes for website.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWebsiteBytes() {
      java.lang.Object ref = website_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        website_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIRTH_PLACE_FIELD_NUMBER = 8;
    private volatile java.lang.Object birthPlace_;
    /**
     * <code>optional string birth_place = 8;</code>
     * @return Whether the birthPlace field is set.
     */
    @java.lang.Override
    public boolean hasBirthPlace() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string birth_place = 8;</code>
     * @return The birthPlace.
     */
    @java.lang.Override
    public java.lang.String getBirthPlace() {
      java.lang.Object ref = birthPlace_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        birthPlace_ = s;
        return s;
      }
    }
    /**
     * <code>optional string birth_place = 8;</code>
     * @return The bytes for birthPlace.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBirthPlaceBytes() {
      java.lang.Object ref = birthPlace_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birthPlace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEIGHT_FIELD_NUMBER = 9;
    private int weight_;
    /**
     * <code>optional uint32 weight = 9;</code>
     * @return Whether the weight field is set.
     */
    @java.lang.Override
    public boolean hasWeight() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint32 weight = 9;</code>
     * @return The weight.
     */
    @java.lang.Override
    public int getWeight() {
      return weight_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 10;
    private int height_;
    /**
     * <code>optional uint32 height = 10;</code>
     * @return Whether the height field is set.
     */
    @java.lang.Override
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint32 height = 10;</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
      }
      if (!getCountryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, country_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(5, getBirthDate());
      }
      if (!getPhotoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, photo_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, website_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, birthPlace_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt32(9, weight_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt32(10, height_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
      }
      if (!getCountryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, country_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getBirthDate());
      }
      if (!getPhotoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, photo_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, website_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, birthPlace_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, weight_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, height_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider)) {
        return super.equals(obj);
      }
      io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider other = (io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getCountry()
          .equals(other.getCountry())) return false;
      if (hasBirthDate() != other.hasBirthDate()) return false;
      if (hasBirthDate()) {
        if (!getBirthDate()
            .equals(other.getBirthDate())) return false;
      }
      if (!getPhoto()
          .equals(other.getPhoto())) return false;
      if (hasWebsite() != other.hasWebsite()) return false;
      if (hasWebsite()) {
        if (!getWebsite()
            .equals(other.getWebsite())) return false;
      }
      if (hasBirthPlace() != other.hasBirthPlace()) return false;
      if (hasBirthPlace()) {
        if (!getBirthPlace()
            .equals(other.getBirthPlace())) return false;
      }
      if (hasWeight() != other.hasWeight()) return false;
      if (hasWeight()) {
        if (getWeight()
            != other.getWeight()) return false;
      }
      if (hasHeight() != other.hasHeight()) return false;
      if (hasHeight()) {
        if (getHeight()
            != other.getHeight()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry().hashCode();
      if (hasBirthDate()) {
        hash = (37 * hash) + BIRTH_DATE_FIELD_NUMBER;
        hash = (53 * hash) + getBirthDate().hashCode();
      }
      hash = (37 * hash) + PHOTO_FIELD_NUMBER;
      hash = (53 * hash) + getPhoto().hashCode();
      if (hasWebsite()) {
        hash = (37 * hash) + WEBSITE_FIELD_NUMBER;
        hash = (53 * hash) + getWebsite().hashCode();
      }
      if (hasBirthPlace()) {
        hash = (37 * hash) + BIRTH_PLACE_FIELD_NUMBER;
        hash = (53 * hash) + getBirthPlace().hashCode();
      }
      if (hasWeight()) {
        hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getWeight();
      }
      if (hasHeight()) {
        hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getHeight();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.github.patxibocos.pcsscraper.protobuf.rider.Rider}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.github.patxibocos.pcsscraper.protobuf.rider.Rider)
        io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.RiderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_rider_Rider_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_rider_Rider_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider.class, io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider.Builder.class);
      }

      // Construct using io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBirthDateFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        firstName_ = "";

        lastName_ = "";

        country_ = "";

        if (birthDateBuilder_ == null) {
          birthDate_ = null;
        } else {
          birthDateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        photo_ = "";

        website_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        birthPlace_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        weight_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_rider_Rider_descriptor;
      }

      @java.lang.Override
      public io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider getDefaultInstanceForType() {
        return io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider build() {
        io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider buildPartial() {
        io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider result = new io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.country_ = country_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (birthDateBuilder_ == null) {
            result.birthDate_ = birthDate_;
          } else {
            result.birthDate_ = birthDateBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        result.photo_ = photo_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.website_ = website_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.birthPlace_ = birthPlace_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.weight_ = weight_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.height_ = height_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider) {
          return mergeFrom((io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider other) {
        if (other == io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (!other.getCountry().isEmpty()) {
          country_ = other.country_;
          onChanged();
        }
        if (other.hasBirthDate()) {
          mergeBirthDate(other.getBirthDate());
        }
        if (!other.getPhoto().isEmpty()) {
          photo_ = other.photo_;
          onChanged();
        }
        if (other.hasWebsite()) {
          bitField0_ |= 0x00000002;
          website_ = other.website_;
          onChanged();
        }
        if (other.hasBirthPlace()) {
          bitField0_ |= 0x00000004;
          birthPlace_ = other.birthPlace_;
          onChanged();
        }
        if (other.hasWeight()) {
          setWeight(other.getWeight());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string first_name = 2;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string first_name = 2;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string first_name = 2;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 2;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string last_name = 3;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string last_name = 3;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string last_name = 3;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 3;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object country_ = "";
      /**
       * <code>string country = 4;</code>
       * @return The country.
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string country = 4;</code>
       * @return The bytes for country.
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string country = 4;</code>
       * @param value The country to set.
       * @return This builder for chaining.
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string country = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCountry() {
        
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <code>string country = 4;</code>
       * @param value The bytes for country to set.
       * @return This builder for chaining.
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        country_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp birthDate_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> birthDateBuilder_;
      /**
       * <code>optional .google.protobuf.Timestamp birth_date = 5;</code>
       * @return Whether the birthDate field is set.
       */
      public boolean hasBirthDate() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .google.protobuf.Timestamp birth_date = 5;</code>
       * @return The birthDate.
       */
      public com.google.protobuf.Timestamp getBirthDate() {
        if (birthDateBuilder_ == null) {
          return birthDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthDate_;
        } else {
          return birthDateBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp birth_date = 5;</code>
       */
      public Builder setBirthDate(com.google.protobuf.Timestamp value) {
        if (birthDateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          birthDate_ = value;
          onChanged();
        } else {
          birthDateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp birth_date = 5;</code>
       */
      public Builder setBirthDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (birthDateBuilder_ == null) {
          birthDate_ = builderForValue.build();
          onChanged();
        } else {
          birthDateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp birth_date = 5;</code>
       */
      public Builder mergeBirthDate(com.google.protobuf.Timestamp value) {
        if (birthDateBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              birthDate_ != null &&
              birthDate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            birthDate_ =
              com.google.protobuf.Timestamp.newBuilder(birthDate_).mergeFrom(value).buildPartial();
          } else {
            birthDate_ = value;
          }
          onChanged();
        } else {
          birthDateBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp birth_date = 5;</code>
       */
      public Builder clearBirthDate() {
        if (birthDateBuilder_ == null) {
          birthDate_ = null;
          onChanged();
        } else {
          birthDateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp birth_date = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getBirthDateBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBirthDateFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Timestamp birth_date = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getBirthDateOrBuilder() {
        if (birthDateBuilder_ != null) {
          return birthDateBuilder_.getMessageOrBuilder();
        } else {
          return birthDate_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : birthDate_;
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp birth_date = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getBirthDateFieldBuilder() {
        if (birthDateBuilder_ == null) {
          birthDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getBirthDate(),
                  getParentForChildren(),
                  isClean());
          birthDate_ = null;
        }
        return birthDateBuilder_;
      }

      private java.lang.Object photo_ = "";
      /**
       * <code>string photo = 6;</code>
       * @return The photo.
       */
      public java.lang.String getPhoto() {
        java.lang.Object ref = photo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          photo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string photo = 6;</code>
       * @return The bytes for photo.
       */
      public com.google.protobuf.ByteString
          getPhotoBytes() {
        java.lang.Object ref = photo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          photo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string photo = 6;</code>
       * @param value The photo to set.
       * @return This builder for chaining.
       */
      public Builder setPhoto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        photo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string photo = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhoto() {
        
        photo_ = getDefaultInstance().getPhoto();
        onChanged();
        return this;
      }
      /**
       * <code>string photo = 6;</code>
       * @param value The bytes for photo to set.
       * @return This builder for chaining.
       */
      public Builder setPhotoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        photo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object website_ = "";
      /**
       * <code>optional string website = 7;</code>
       * @return Whether the website field is set.
       */
      public boolean hasWebsite() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string website = 7;</code>
       * @return The website.
       */
      public java.lang.String getWebsite() {
        java.lang.Object ref = website_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          website_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string website = 7;</code>
       * @return The bytes for website.
       */
      public com.google.protobuf.ByteString
          getWebsiteBytes() {
        java.lang.Object ref = website_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          website_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string website = 7;</code>
       * @param value The website to set.
       * @return This builder for chaining.
       */
      public Builder setWebsite(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        website_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string website = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearWebsite() {
        bitField0_ = (bitField0_ & ~0x00000002);
        website_ = getDefaultInstance().getWebsite();
        onChanged();
        return this;
      }
      /**
       * <code>optional string website = 7;</code>
       * @param value The bytes for website to set.
       * @return This builder for chaining.
       */
      public Builder setWebsiteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000002;
        website_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object birthPlace_ = "";
      /**
       * <code>optional string birth_place = 8;</code>
       * @return Whether the birthPlace field is set.
       */
      public boolean hasBirthPlace() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string birth_place = 8;</code>
       * @return The birthPlace.
       */
      public java.lang.String getBirthPlace() {
        java.lang.Object ref = birthPlace_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          birthPlace_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string birth_place = 8;</code>
       * @return The bytes for birthPlace.
       */
      public com.google.protobuf.ByteString
          getBirthPlaceBytes() {
        java.lang.Object ref = birthPlace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          birthPlace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string birth_place = 8;</code>
       * @param value The birthPlace to set.
       * @return This builder for chaining.
       */
      public Builder setBirthPlace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        birthPlace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string birth_place = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearBirthPlace() {
        bitField0_ = (bitField0_ & ~0x00000004);
        birthPlace_ = getDefaultInstance().getBirthPlace();
        onChanged();
        return this;
      }
      /**
       * <code>optional string birth_place = 8;</code>
       * @param value The bytes for birthPlace to set.
       * @return This builder for chaining.
       */
      public Builder setBirthPlaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000004;
        birthPlace_ = value;
        onChanged();
        return this;
      }

      private int weight_ ;
      /**
       * <code>optional uint32 weight = 9;</code>
       * @return Whether the weight field is set.
       */
      @java.lang.Override
      public boolean hasWeight() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional uint32 weight = 9;</code>
       * @return The weight.
       */
      @java.lang.Override
      public int getWeight() {
        return weight_;
      }
      /**
       * <code>optional uint32 weight = 9;</code>
       * @param value The weight to set.
       * @return This builder for chaining.
       */
      public Builder setWeight(int value) {
        bitField0_ |= 0x00000008;
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 weight = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeight() {
        bitField0_ = (bitField0_ & ~0x00000008);
        weight_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>optional uint32 height = 10;</code>
       * @return Whether the height field is set.
       */
      @java.lang.Override
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional uint32 height = 10;</code>
       * @return The height.
       */
      @java.lang.Override
      public int getHeight() {
        return height_;
      }
      /**
       * <code>optional uint32 height = 10;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000010;
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 height = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000010);
        height_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.github.patxibocos.pcsscraper.protobuf.rider.Rider)
    }

    // @@protoc_insertion_point(class_scope:io.github.patxibocos.pcsscraper.protobuf.rider.Rider)
    private static final io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider();
    }

    public static io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Rider>
        PARSER = new com.google.protobuf.AbstractParser<Rider>() {
      @java.lang.Override
      public Rider parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Rider(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Rider> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Rider> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.patxibocos.pcsscraper.protobuf.rider.RiderOuterClass.Rider getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_patxibocos_pcsscraper_protobuf_rider_Rider_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_patxibocos_pcsscraper_protobuf_rider_Rider_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032src/main/proto/rider.proto\022.io.github." +
      "patxibocos.pcsscraper.protobuf.rider\032\037go" +
      "ogle/protobuf/timestamp.proto\"\252\002\n\005Rider\022" +
      "\n\n\002id\030\001 \001(\t\022\022\n\nfirst_name\030\002 \001(\t\022\021\n\tlast_" +
      "name\030\003 \001(\t\022\017\n\007country\030\004 \001(\t\0223\n\nbirth_dat" +
      "e\030\005 \001(\0132\032.google.protobuf.TimestampH\000\210\001\001" +
      "\022\r\n\005photo\030\006 \001(\t\022\024\n\007website\030\007 \001(\tH\001\210\001\001\022\030\n" +
      "\013birth_place\030\010 \001(\tH\002\210\001\001\022\023\n\006weight\030\t \001(\rH" +
      "\003\210\001\001\022\023\n\006height\030\n \001(\rH\004\210\001\001B\r\n\013_birth_date" +
      "B\n\n\010_websiteB\016\n\014_birth_placeB\t\n\007_weightB" +
      "\t\n\007_heightb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_io_github_patxibocos_pcsscraper_protobuf_rider_Rider_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_github_patxibocos_pcsscraper_protobuf_rider_Rider_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_patxibocos_pcsscraper_protobuf_rider_Rider_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Country", "BirthDate", "Photo", "Website", "BirthPlace", "Weight", "Height", "BirthDate", "Website", "BirthPlace", "Weight", "Height", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
