//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/proto/cycling_data.proto

package io.github.patxibocos.pcsscraper.protobuf;

@kotlin.jvm.JvmSynthetic
inline fun cyclingData(block: io.github.patxibocos.pcsscraper.protobuf.CyclingDataKt.Dsl.() -> Unit): io.github.patxibocos.pcsscraper.protobuf.CyclingDataOuterClass.CyclingData =
  io.github.patxibocos.pcsscraper.protobuf.CyclingDataKt.Dsl._create(io.github.patxibocos.pcsscraper.protobuf.CyclingDataOuterClass.CyclingData.newBuilder()).apply { block() }._build()
object CyclingDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: io.github.patxibocos.pcsscraper.protobuf.CyclingDataOuterClass.CyclingData.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.github.patxibocos.pcsscraper.protobuf.CyclingDataOuterClass.CyclingData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.github.patxibocos.pcsscraper.protobuf.CyclingDataOuterClass.CyclingData = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class TeamsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
     */
     val teams: com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team, TeamsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getTeamsList()
      )
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
     * @param value The teams to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTeams")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team, TeamsProxy>.add(value: io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team) {
      _builder.addTeams(value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
     * @param value The teams to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTeams")
    inline operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team, TeamsProxy>.plusAssign(value: io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team) {
      add(value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
     * @param values The teams to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTeams")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team, TeamsProxy>.addAll(values: kotlin.collections.Iterable<io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team>) {
      _builder.addAllTeams(values)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
     * @param values The teams to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTeams")
    inline operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team, TeamsProxy>.plusAssign(values: kotlin.collections.Iterable<io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team>) {
      addAll(values)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
     * @param index The index to set the value at.
     * @param value The teams to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTeams")
    operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team, TeamsProxy>.set(index: kotlin.Int, value: io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team) {
      _builder.setTeams(index, value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Team teams = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTeams")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.TeamOuterClass.Team, TeamsProxy>.clear() {
      _builder.clearTeams()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class RidersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Rider riders = 2;</code>
     */
     val riders: com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider, RidersProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getRidersList()
      )
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Rider riders = 2;</code>
     * @param value The riders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRiders")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider, RidersProxy>.add(value: io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider) {
      _builder.addRiders(value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Rider riders = 2;</code>
     * @param value The riders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRiders")
    inline operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider, RidersProxy>.plusAssign(value: io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider) {
      add(value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Rider riders = 2;</code>
     * @param values The riders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRiders")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider, RidersProxy>.addAll(values: kotlin.collections.Iterable<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider>) {
      _builder.addAllRiders(values)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Rider riders = 2;</code>
     * @param values The riders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRiders")
    inline operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider, RidersProxy>.plusAssign(values: kotlin.collections.Iterable<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider>) {
      addAll(values)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Rider riders = 2;</code>
     * @param index The index to set the value at.
     * @param value The riders to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRiders")
    operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider, RidersProxy>.set(index: kotlin.Int, value: io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider) {
      _builder.setRiders(index, value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Rider riders = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRiders")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider, RidersProxy>.clear() {
      _builder.clearRiders()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class RacesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 3;</code>
     */
     val races: com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race, RacesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getRacesList()
      )
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 3;</code>
     * @param value The races to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRaces")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race, RacesProxy>.add(value: io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race) {
      _builder.addRaces(value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 3;</code>
     * @param value The races to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRaces")
    inline operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race, RacesProxy>.plusAssign(value: io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race) {
      add(value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 3;</code>
     * @param values The races to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRaces")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race, RacesProxy>.addAll(values: kotlin.collections.Iterable<io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race>) {
      _builder.addAllRaces(values)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 3;</code>
     * @param values The races to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRaces")
    inline operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race, RacesProxy>.plusAssign(values: kotlin.collections.Iterable<io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race>) {
      addAll(values)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 3;</code>
     * @param index The index to set the value at.
     * @param value The races to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRaces")
    operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race, RacesProxy>.set(index: kotlin.Int, value: io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race) {
      _builder.setRaces(index, value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Race races = 3;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRaces")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.Race, RacesProxy>.clear() {
      _builder.clearRaces()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun io.github.patxibocos.pcsscraper.protobuf.CyclingDataOuterClass.CyclingData.copy(block: io.github.patxibocos.pcsscraper.protobuf.CyclingDataKt.Dsl.() -> Unit): io.github.patxibocos.pcsscraper.protobuf.CyclingDataOuterClass.CyclingData =
  io.github.patxibocos.pcsscraper.protobuf.CyclingDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()
