//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/proto/race.proto

package io.github.patxibocos.pcsscraper.protobuf;

@kotlin.jvm.JvmSynthetic
inline fun riderParticipation(block: io.github.patxibocos.pcsscraper.protobuf.RiderParticipationKt.Dsl.() -> Unit): io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RiderParticipation =
  io.github.patxibocos.pcsscraper.protobuf.RiderParticipationKt.Dsl._create(io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RiderParticipation.newBuilder()).apply { block() }._build()
object RiderParticipationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RiderParticipation.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RiderParticipation.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RiderParticipation = _builder.build()

    /**
     * <code>string rider_id = 1;</code>
     */
    var riderId: kotlin.String
      @JvmName("getRiderId")
      get() = _builder.getRiderId()
      @JvmName("setRiderId")
      set(value) {
        _builder.setRiderId(value)
      }
    /**
     * <code>string rider_id = 1;</code>
     */
    fun clearRiderId() {
      _builder.clearRiderId()
    }

    /**
     * <code>optional uint32 number = 2;</code>
     */
    var number: kotlin.Int
      @JvmName("getNumber")
      get() = _builder.getNumber()
      @JvmName("setNumber")
      set(value) {
        _builder.setNumber(value)
      }
    /**
     * <code>optional uint32 number = 2;</code>
     */
    fun clearNumber() {
      _builder.clearNumber()
    }
    /**
     * <code>optional uint32 number = 2;</code>
     * @return Whether the number field is set.
     */
    fun hasNumber(): kotlin.Boolean {
      return _builder.hasNumber()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RiderParticipation.copy(block: io.github.patxibocos.pcsscraper.protobuf.RiderParticipationKt.Dsl.() -> Unit): io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RiderParticipation =
  io.github.patxibocos.pcsscraper.protobuf.RiderParticipationKt.Dsl._create(this.toBuilder()).apply { block() }._build()
