//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: rider.proto

package io.github.patxibocos.pcsscraper.protobuf;

@kotlin.jvm.JvmSynthetic
inline fun riders(block: io.github.patxibocos.pcsscraper.protobuf.RidersKt.Dsl.() -> Unit): io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Riders =
  io.github.patxibocos.pcsscraper.protobuf.RidersKt.Dsl._create(io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Riders.newBuilder()).apply { block() }._build()
object RidersKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Riders.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Riders.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Riders = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class RidersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Rider riders = 1;</code>
     */
     val riders: com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider, RidersProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getRidersList()
      )
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Rider riders = 1;</code>
     * @param value The riders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addRiders")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider, RidersProxy>.add(value: io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider) {
      _builder.addRiders(value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Rider riders = 1;</code>
     * @param value The riders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignRiders")
    inline operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider, RidersProxy>.plusAssign(value: io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider) {
      add(value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Rider riders = 1;</code>
     * @param values The riders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllRiders")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider, RidersProxy>.addAll(values: kotlin.collections.Iterable<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider>) {
      _builder.addAllRiders(values)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Rider riders = 1;</code>
     * @param values The riders to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllRiders")
    inline operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider, RidersProxy>.plusAssign(values: kotlin.collections.Iterable<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider>) {
      addAll(values)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Rider riders = 1;</code>
     * @param index The index to set the value at.
     * @param value The riders to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setRiders")
    operator fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider, RidersProxy>.set(index: kotlin.Int, value: io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider) {
      _builder.setRiders(index, value)
    }/**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.Rider riders = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearRiders")
    fun com.google.protobuf.kotlin.DslList<io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Rider, RidersProxy>.clear() {
      _builder.clearRiders()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Riders.copy(block: io.github.patxibocos.pcsscraper.protobuf.RidersKt.Dsl.() -> Unit): io.github.patxibocos.pcsscraper.protobuf.RiderOuterClass.Riders =
  io.github.patxibocos.pcsscraper.protobuf.RidersKt.Dsl._create(this.toBuilder()).apply { block() }._build()
