//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: race.proto

package io.github.patxibocos.pcsscraper.protobuf;

@kotlin.jvm.JvmSynthetic
inline fun riderResult(block: io.github.patxibocos.pcsscraper.protobuf.RiderResultKt.Dsl.() -> Unit): io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RiderResult =
  io.github.patxibocos.pcsscraper.protobuf.RiderResultKt.Dsl._create(io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RiderResult.newBuilder()).apply { block() }._build()
object RiderResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RiderResult.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RiderResult.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RiderResult = _builder.build()

    /**
     * <code>uint32 position = 1;</code>
     */
    var position: kotlin.Int
      @JvmName("getPosition")
      get() = _builder.getPosition()
      @JvmName("setPosition")
      set(value) {
        _builder.setPosition(value)
      }
    /**
     * <code>uint32 position = 1;</code>
     */
    fun clearPosition() {
      _builder.clearPosition()
    }

    /**
     * <code>string rider_id = 2;</code>
     */
    var riderId: kotlin.String
      @JvmName("getRiderId")
      get() = _builder.getRiderId()
      @JvmName("setRiderId")
      set(value) {
        _builder.setRiderId(value)
      }
    /**
     * <code>string rider_id = 2;</code>
     */
    fun clearRiderId() {
      _builder.clearRiderId()
    }

    /**
     * <code>int64 time = 3;</code>
     */
    var time: kotlin.Long
      @JvmName("getTime")
      get() = _builder.getTime()
      @JvmName("setTime")
      set(value) {
        _builder.setTime(value)
      }
    /**
     * <code>int64 time = 3;</code>
     */
    fun clearTime() {
      _builder.clearTime()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RiderResult.copy(block: io.github.patxibocos.pcsscraper.protobuf.RiderResultKt.Dsl.() -> Unit): io.github.patxibocos.pcsscraper.protobuf.RaceOuterClass.RiderResult =
  io.github.patxibocos.pcsscraper.protobuf.RiderResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()
