// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/teams.proto

package io.github.patxibocos.pcsscraper.protobuf.team;

public final class TeamsOuterClass {
  private TeamsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TeamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.github.patxibocos.pcsscraper.protobuf.team.Teams)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
     */
    java.util.List<io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team> 
        getTeamsList();
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
     */
    io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team getTeams(int index);
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
     */
    int getTeamsCount();
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
     */
    java.util.List<? extends io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.TeamOrBuilder> 
        getTeamsOrBuilderList();
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
     */
    io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.TeamOrBuilder getTeamsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code io.github.patxibocos.pcsscraper.protobuf.team.Teams}
   */
  public static final class Teams extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.github.patxibocos.pcsscraper.protobuf.team.Teams)
      TeamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Teams.newBuilder() to construct.
    private Teams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Teams() {
      teams_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Teams();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Teams(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                teams_ = new java.util.ArrayList<io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team>();
                mutable_bitField0_ |= 0x00000001;
              }
              teams_.add(
                  input.readMessage(io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          teams_ = java.util.Collections.unmodifiableList(teams_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_team_Teams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_team_Teams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams.class, io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams.Builder.class);
    }

    public static final int TEAMS_FIELD_NUMBER = 1;
    private java.util.List<io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team> teams_;
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
     */
    @java.lang.Override
    public java.util.List<io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team> getTeamsList() {
      return teams_;
    }
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.TeamOrBuilder> 
        getTeamsOrBuilderList() {
      return teams_;
    }
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
     */
    @java.lang.Override
    public int getTeamsCount() {
      return teams_.size();
    }
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
     */
    @java.lang.Override
    public io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team getTeams(int index) {
      return teams_.get(index);
    }
    /**
     * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
     */
    @java.lang.Override
    public io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.TeamOrBuilder getTeamsOrBuilder(
        int index) {
      return teams_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < teams_.size(); i++) {
        output.writeMessage(1, teams_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < teams_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, teams_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams)) {
        return super.equals(obj);
      }
      io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams other = (io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams) obj;

      if (!getTeamsList()
          .equals(other.getTeamsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTeamsCount() > 0) {
        hash = (37 * hash) + TEAMS_FIELD_NUMBER;
        hash = (53 * hash) + getTeamsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.github.patxibocos.pcsscraper.protobuf.team.Teams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.github.patxibocos.pcsscraper.protobuf.team.Teams)
        io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.TeamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_team_Teams_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_team_Teams_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams.class, io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams.Builder.class);
      }

      // Construct using io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTeamsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (teamsBuilder_ == null) {
          teams_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          teamsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.internal_static_io_github_patxibocos_pcsscraper_protobuf_team_Teams_descriptor;
      }

      @java.lang.Override
      public io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams getDefaultInstanceForType() {
        return io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams build() {
        io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams buildPartial() {
        io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams result = new io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams(this);
        int from_bitField0_ = bitField0_;
        if (teamsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            teams_ = java.util.Collections.unmodifiableList(teams_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.teams_ = teams_;
        } else {
          result.teams_ = teamsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams) {
          return mergeFrom((io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams other) {
        if (other == io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams.getDefaultInstance()) return this;
        if (teamsBuilder_ == null) {
          if (!other.teams_.isEmpty()) {
            if (teams_.isEmpty()) {
              teams_ = other.teams_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTeamsIsMutable();
              teams_.addAll(other.teams_);
            }
            onChanged();
          }
        } else {
          if (!other.teams_.isEmpty()) {
            if (teamsBuilder_.isEmpty()) {
              teamsBuilder_.dispose();
              teamsBuilder_ = null;
              teams_ = other.teams_;
              bitField0_ = (bitField0_ & ~0x00000001);
              teamsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTeamsFieldBuilder() : null;
            } else {
              teamsBuilder_.addAllMessages(other.teams_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team> teams_ =
        java.util.Collections.emptyList();
      private void ensureTeamsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          teams_ = new java.util.ArrayList<io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team>(teams_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team, io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team.Builder, io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.TeamOrBuilder> teamsBuilder_;

      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public java.util.List<io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team> getTeamsList() {
        if (teamsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(teams_);
        } else {
          return teamsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public int getTeamsCount() {
        if (teamsBuilder_ == null) {
          return teams_.size();
        } else {
          return teamsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team getTeams(int index) {
        if (teamsBuilder_ == null) {
          return teams_.get(index);
        } else {
          return teamsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public Builder setTeams(
          int index, io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team value) {
        if (teamsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeamsIsMutable();
          teams_.set(index, value);
          onChanged();
        } else {
          teamsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public Builder setTeams(
          int index, io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team.Builder builderForValue) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          teams_.set(index, builderForValue.build());
          onChanged();
        } else {
          teamsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public Builder addTeams(io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team value) {
        if (teamsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeamsIsMutable();
          teams_.add(value);
          onChanged();
        } else {
          teamsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public Builder addTeams(
          int index, io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team value) {
        if (teamsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeamsIsMutable();
          teams_.add(index, value);
          onChanged();
        } else {
          teamsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public Builder addTeams(
          io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team.Builder builderForValue) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          teams_.add(builderForValue.build());
          onChanged();
        } else {
          teamsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public Builder addTeams(
          int index, io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team.Builder builderForValue) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          teams_.add(index, builderForValue.build());
          onChanged();
        } else {
          teamsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public Builder addAllTeams(
          java.lang.Iterable<? extends io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team> values) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, teams_);
          onChanged();
        } else {
          teamsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public Builder clearTeams() {
        if (teamsBuilder_ == null) {
          teams_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          teamsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public Builder removeTeams(int index) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          teams_.remove(index);
          onChanged();
        } else {
          teamsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team.Builder getTeamsBuilder(
          int index) {
        return getTeamsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.TeamOrBuilder getTeamsOrBuilder(
          int index) {
        if (teamsBuilder_ == null) {
          return teams_.get(index);  } else {
          return teamsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public java.util.List<? extends io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.TeamOrBuilder> 
           getTeamsOrBuilderList() {
        if (teamsBuilder_ != null) {
          return teamsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(teams_);
        }
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team.Builder addTeamsBuilder() {
        return getTeamsFieldBuilder().addBuilder(
            io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team.getDefaultInstance());
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team.Builder addTeamsBuilder(
          int index) {
        return getTeamsFieldBuilder().addBuilder(
            index, io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team.getDefaultInstance());
      }
      /**
       * <code>repeated .io.github.patxibocos.pcsscraper.protobuf.team.Team teams = 1;</code>
       */
      public java.util.List<io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team.Builder> 
           getTeamsBuilderList() {
        return getTeamsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team, io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team.Builder, io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.TeamOrBuilder> 
          getTeamsFieldBuilder() {
        if (teamsBuilder_ == null) {
          teamsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team, io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.Team.Builder, io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.TeamOrBuilder>(
                  teams_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          teams_ = null;
        }
        return teamsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.github.patxibocos.pcsscraper.protobuf.team.Teams)
    }

    // @@protoc_insertion_point(class_scope:io.github.patxibocos.pcsscraper.protobuf.team.Teams)
    private static final io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams();
    }

    public static io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Teams>
        PARSER = new com.google.protobuf.AbstractParser<Teams>() {
      @java.lang.Override
      public Teams parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Teams(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Teams> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Teams> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.patxibocos.pcsscraper.protobuf.team.TeamsOuterClass.Teams getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_patxibocos_pcsscraper_protobuf_team_Teams_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_patxibocos_pcsscraper_protobuf_team_Teams_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032src/main/proto/teams.proto\022-io.github." +
      "patxibocos.pcsscraper.protobuf.team\032\031src" +
      "/main/proto/team.proto\"K\n\005Teams\022B\n\005teams" +
      "\030\001 \003(\01323.io.github.patxibocos.pcsscraper" +
      ".protobuf.team.Teamb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.getDescriptor(),
        });
    internal_static_io_github_patxibocos_pcsscraper_protobuf_team_Teams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_github_patxibocos_pcsscraper_protobuf_team_Teams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_patxibocos_pcsscraper_protobuf_team_Teams_descriptor,
        new java.lang.String[] { "Teams", });
    io.github.patxibocos.pcsscraper.protobuf.team.TeamOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
