name: scrap

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set GOOGLE_APPLICATION_CREDENTIALS environment variable
        run: |
          gpg --version
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebase.service-account.json.asc
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.FIREBASE_SERVICE_ACCOUNT_PASSPHRASE }}" --output firebase.service-account.json firebase.service-account.json.asc
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(echo $(pwd)/firebase.service-account.json)" >> $GITHUB_ENV
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16'
      - name: Build
        run: ./gradlew build
      - name: Run scraper
        run: java -jar build/libs/pcs-scraper.jar -s 2022 -d out -f firebase