name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Test
        run: ./gradlew test

      - name: Build Jar
        run: ./gradlew shadowJar

      - name: Copy binaries
        run: mkdir -p release && mv -f scraper/build/libs/scraper.jar release && mv -f diff-publisher/build/libs/diff-publisher.jar release

      - name: Commit binaries
        uses: EndBug/add-and-commit@v9
        with:
          add: 'release'
          message: 'Update release artifacts'
          tag_push: '--force'