name: release

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  scrap:
    uses: ./.github/workflows/run.yaml
    with:
      formats: -f sqlite -f json -f protobuf
      upload-artifact: true
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      FIREBASE_SERVICE_ACCOUNT_PASSPHRASE: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PASSPHRASE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_S3_OBJECT_KEY: ${{ secrets.AWS_S3_OBJECT_KEY }}
  release:
    needs: scrap
    runs-on: ubuntu-latest
    steps:
      - name: Download output
        uses: actions/download-artifact@v3
        with:
          name: scraper
          path: out
      - name: Set current date as env variable
        run: echo "TODAY=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ env.TODAY }}
          tag_name: v${{ env.TODAY }}
          files: |
            out/db.sqlite
            out/teams.json
            out/riders.json
            out/races.json
            out/cycling.data