name: run

on:
  workflow_call:
    inputs:
      formats:
        required: true
        type: string
      upload-artifact:
        required: false
        type: boolean
        default: false
    secrets:
      FIREBASE_SERVICE_ACCOUNT:
        required: true
      FIREBASE_SERVICE_ACCOUNT_PASSPHRASE:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_S3_BUCKET:
        required: true
      AWS_S3_OBJECT_KEY:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16'
      - name: Build pcs-scraper
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build
          gradle-version: wrapper
      - name: Set GOOGLE_APPLICATION_CREDENTIALS environment variable
        run: |
          gpg --version
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebase.service-account.json.asc
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.FIREBASE_SERVICE_ACCOUNT_PASSPHRASE }}" --output firebase.service-account.json firebase.service-account.json.asc
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(echo $(pwd)/firebase.service-account.json)" >> $GITHUB_ENV
      - name: Run scraper
        run: java -jar build/libs/pcs-scraper.jar -s 2022 -c cache -d out ${{ inputs.formats }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_OBJECT_KEY: ${{ secrets.AWS_S3_OBJECT_KEY }}
      - name: Upload output
        uses: actions/upload-artifact@v3
        if: ${{ inputs.upload-artifact }}
        with:
          name: scraper
          path: out/