name: scrap

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  scrap:
    uses: ./.github/workflows/run.yml
    with:
      formats: -f firebase -f s3
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      FIREBASE_SERVICE_ACCOUNT_PASSPHRASE: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PASSPHRASE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_S3_OBJECT_KEY: ${{ secrets.AWS_S3_OBJECT_KEY }}